version: '3'
services:
  proxy:
    build: .
    image: maayanlab/proxy:1.2.12
    platform: linux/amd64
    environment:
      # the anticipated name of the server host
      - nginx_server_name=localhost

      # HTTP Basic Auth
      # - nginx_basic_auth=username:password

      # SSL (when ssl is enabled, http is forwarded to ssl)
      # - nginx_ssl=1

      # LetsEncrypt for automatic cert verification (also see: volumes)
      # - nginx_ssl_letsencrypt=1
      # - letsencrypt_email=your@email.com
      # - letsencrypt_staging=0
      # OR certs in pem format
      # - nginx_ssl_key=(replaces ; with \n)
      # - nginx_ssl_crt=(replaces ; with \n)
      # OR provide them in directory:
      # - nginx_ssl_root=/ssl/directory/
      #  tls.key, tls.crt

      # disable automatic redirecting http => https
      # - nginx_ssl_redirect=0
  
      # proxy_pass rules
      - nginx_proxy_00=/basepath http://backendsever:8080/
      - nginx_proxy_01=/(.*) https://backendfallback/$$1
      # nginx_proxy_xxx: ...

      # rewrite rules (302)
      - nginx_redirect_00=/redirectpath http://new/loc
      - nginx_redirect_01=/redirect/expr/(.*) http://new/loc/$$1
      # nginx_redirect_xxx: ...

      # html redirect (for annoying situations -- return 200 but redirect w/ javascript)
      # - nginx_html_redirect_xx=/redirectpath/(.*) http://new/loc/$$1
  
      # add compression
      # - nginx_gzip=1

      # configure ports
      # - nginx_http_port=5080
      # - nginx_https_port=5443

      # configure timeouts
      # - nginx_timeout=300

      # disable buffering
      # - nginx_buffering=0
    ports:
      # http port
      - 80:80
      # ssl port
      # - 443:443
    # volumes:
      # /etc/letsencrypt/ should be persistent as it stores your ssl keys
      # - letsencrypt:/etc/letsencrypt/
# volumes:
#   letsencrypt:
